//  This file has been auto generated by xxxx.py
//  Content sourced from https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/Multiprotocol/Multiprotocol.h

typedef unsigned int (*uint16_function_t) (void);	//pointer to a function with no parameters which return an unsigned int
typedef void     (*void_function_t  ) (void);	//pointer to a function with no parameters which returns nothing

struct radio_protocol_definition {
  unsigned int protocol;
  const char *ProtoString;
  const char *SubProtoString;
  unsigned int nbrSubProto;
  unsigned int optionType;
  unsigned int failsafe;
  unsigned int chMap;
  unsigned int rfSwitch;
  void_function_t		Init;
  uint16_function_t	CallBack;
};
